### ISSUE TITLE
Where is the display direction set

### ISSUE THREAD

**Issue by 627514** [AppLovin/AppLovin-MAX-Unity-Plugin#149]
I searched through the documents and couldn't find the parameters where I could set the display direction

help

**Comment by thomasmso** [comment]
Could you elaborate what you mean by "display direction"?

**Comment by hutao1230** [comment]
Can I switch between horizontal and vertical screens？

**Comment by hutao1230** [comment]
> 您能否详细说明“显示方向”的含义？

Can I switch between horizontal and vertical screens？

**Comment by guowei0306** [comment]
Hi 如果想问的是视频广告的方向，这个开发者不能控制（没有SDK设置方法），因为统一由MAX SDK根据应用屏幕方向自动适配。如果不是的话，可以详细描述一下你的问题和产品需求嘛？

**Comment by hutao1230** [comment]
> Hi 如果想问的是视频广告的方向，这个开发者不能控制（没有SDK设置方法），因为统一由MAX SDK根据应用屏幕方向自动适配。如果不是的话，可以详细描述一下你的问题和产品需求嘛？
Does it follow the direction of the mobile phone screen? Then I set the horizontal screen and the advertisement is displayed in the vertical screen. What's the matter

**Comment by guowei0306** [comment]
Yes it follows the app orientation. Can you reproduce again and check the ad info with creative debugger? 
See how to: https://dash.applovin.com/documentation/mediation/android/testing-networks/creative-debugger#creative-debugger

Please share the problematic ad response with us so that we can help investigate further. Would be also helpful if you can share a video recording.
