### ISSUE TITLE
Ads are loaded but not showing on iOS

### ISSUE THREAD

**Issue by AVOGames** [AppLovin/AppLovin-MAX-Unity-Plugin#199]
### MAX Plugin Version

5.5.0

### Unity Version

2021.3.10

### Device/Platform Info

iOS 15, 16

### Current Behavior

I tried to load Rewarded Video ads, and it loads ok
 but failed to show with the following error:

`Attempted to display a non-incentivized ad using ALIncentivizedInterstitialAd: [ALAd #11431792 zoneIdentifier=(null), size=[ALAdSize: INTER], type=[ALAdType: VIDEOA]]`

### Expected Behavior

The ad should load and show without errors.

### How to Reproduce

* Clone the DemoApp from this repo.
* Update to **Unity** 2021.3.10
* Update **ExternralDependencyManager** to 1.2.172
* Update **Applovin** to the latest iOS/Android version
* Update scripts with the real APP KEY and UnitID
* in iOS Resolver check:
   "use_frameworks!" 
   "Always add the main target to Podfile"

* Export the build using the iOS platform. 
* Build and Run with Xcode 13.x

When a Rewarded video is loaded, tap on the "show" button.
Observe that no ads are shown. 

Logs show the following error:

`[AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] Attempted to display a non-incentivized ad using ALIncentivizedInterstitialAd: [ALAd #11431792 zoneIdentifier=(null), size=[ALAdSize: INTER], type=[ALAdType: VIDEOA]]`

**Comment by santoshbagadi** [comment]
Hi @AVOGames , the `use_frameworks!` and `Always add the main target to Podfile` are currently not supported by our SDK and need to be disabled. Is there a specific reason for enabling these settings?

**Comment by AVOGames** [comment]
> Hi @AVOGames , the `use_frameworks!` and `Always add the main target to Podfile` are currently not supported by our SDK and need to be disabled. Is there a specific reason for enabling these settings?

Hi,
I'm also trying to integrate other frameworks, and they for some reason can't be found in the main app when these flags are not set.

**Comment by nith666** [comment]
I had the problem that displaying of an interstitial always failed despite being loaded correctly. Disabling both of the settings mentioned by @AVOGames resolved this issue. Don't know why they were checked in the first place, though

**Comment by santoshbagadi** [comment]
@AVOGames , for other frameworks, you can try embedding them to the main target instead of using the `Always add the main target to Podfile`.

**Comment by romas34** [comment]
I had same problem for one my project! Applovin Unity plugin version is 6.3.0. Options "Always add the main target to Podfile" and "Add use_framworks! To podfile" are unchecked! Rewarded ads are loaded, but don't display with error from topic.
[AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] Attempting to display ad with invalid ad type: [ALAd #33460176 zoneIdentifier=(null), size=[ALAdSize: INTER], type=[ALAdType: VIDEOA]]
[AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] NOTE the above error might be due to linking issues with the iOS SDK, causing duplicate classes
Debug [AppLovin MAX] Invoking event: OnRewardedAdFailedToDisplayEvent. Params: xxxxxx, [ErrorInfo code: -5200, message: Attempting to display ad with invalid ad type, latency: 0, adLoadFailureInfo: ], [AdInfo adUnitIdentifier: xxxxxx, adFormat: REWARDED, networkName: AppLovin, networkPlacement: inter_videoa, creativeIdentifier: xxx, placement: , revenue: 0,00178983879089356, revenuePrecision: exact, latency: 0, dspName: ]
Applovin: Rewarded ad failed to display with error code: -5200

What could be the reason?

**Comment by santoshbagadi** [comment]
Could you please share the `Podfile` for the exported project. External Dependency Manager does not save the settings unless `OK` is clicked on the dialog.

**Comment by romas34** [comment]
> Could you please share the `Podfile` for the exported project. External Dependency Manager does not save the settings unless `OK` is clicked on the dialog.

source 'https://cdn.cocoapods.org/'

platform :ios, '13.0'

target 'UnityFramework' do
  pod 'AppLovinMediationBidMachineAdapter', '2.5.1.0.0'
  pod 'AppLovinMediationFacebookAdapter', '6.14.0.1'
  pod 'AppLovinMediationGoogleAdapter', '11.1.0.0'
  pod 'AppLovinMediationInMobiAdapter', '10.6.4.0'
  pod 'AppLovinMediationIronSourceAdapter', '7.8.0.0.1'
  pod 'AppLovinMediationMintegralAdapter', '7.5.8.0.0'
  pod 'AppLovinMediationMyTargetAdapter', '5.20.1.1'
  pod 'AppLovinMediationUnityAdsAdapter', '4.9.3.0'
  pod 'AppLovinMediationVungleAdapter', '7.2.2.0'
  pod 'AppLovinMediationYandexAdapter', '6.1.0.3'
  pod 'AppLovinSDK', '12.3.0'
  pod 'FBSDKCoreKit', '~> 16.0.1'
  pod 'FBSDKCoreKit_Basics', '~> 16.0.1'
  pod 'FBSDKGamingServicesKit', '~> 16.0.1'
  pod 'FBSDKLoginKit', '~> 16.0.1'
  pod 'FBSDKShareKit', '~> 16.0.1'
  pod 'GoogleSignIn', '~> 6.0.2'
  pod 'GoogleUserMessagingPlatform', '2.1.0'
end
target 'Unity-iPhone' do
end

I've already spent the whole day and can't solve this problem.
In my other project, Rewarded advertising has been working for a long time and now too, but there is an option "Add use_frameworks! to Podfile" is checked! 
But this project with checked option "Add use_frameworks! to Podfile" is not assembled in XCode! But your documentation says that these options ("Add use_frameworks! to Podfile" and "Always add the main target to Podfile") should be unchecked!

**Comment by santoshbagadi** [comment]
It looks like `Always add the main target to Podfile` setting change has not been saved. The `target 'Unity-iPhone' do` is still present in the Podfile. Please make sure to hit `OK` after changing the setting in External Dependency Manager settings dialog to make sure that the settings are saved and re-build the project.

**Comment by romas34** [comment]
> It looks like `Always add the main target to Podfile` setting change has not been saved. The `target 'Unity-iPhone' do` is still present in the Podfile. Please make sure to hit `OK` after changing the setting in External Dependency Manager settings dialog to make sure that the settings are saved and re-build the project.

Of course I have everything saved!
I manually removed the line `target 'Unity-iPhone' do` from the Podfile - the result is the same. The same errors occur when trying to display both reworded and banner ads.

**Comment by romas34** [comment]
Errors when banner ads try show (log):

[AppLovinSdk] ERROR [ALSdk] Called with an invalid object type from: (
	0  0x0000000105389010 +[ALUtils assertValidAd:] + 208
	1   0x00000001052c596c -[ALAdView render:] + 60
	2   0x000000010529bc48 __55-[ALAppLovinAdapterAdViewDelegate adService:didLoadAd:]_block_invoke + 456
	3   0x000000010529ba28 -[ALAppLovinAdapterAdViewDelegate adService:didLoadAd:] + 180
	4   UnityFramework                      0x000000010f136d90 __70+[ALDelegateCallbackInvoker invokeAdLoadDelegate:adService:didLoadAd:]_block_invoke + 28
	5   Foundation                          0x000000018f7f4fa8 0D9893A4-5804-3F0D-BB3F-73989EA36AD3 + 1253288
	.............

[AppLovinSdk] ERROR [ALDelegateCallbackInvoker] Unable to notify ad delegate about ad being loaded : Passed an object of type other than ALAd: ALAdServerAd.
Debug [AppLovin MAX] Invoking event: OnBannerAdLoadedEvent. Params: 8axxxxx58, [AdInfo adUnitIdentifier: 8axxx58, adFormat: BANNER, networkName: AppLovin, networkPlacement: banner_regular, creativeIdentifier: 27xxx2, placement: , revenue: 0,000220700964331627, revenuePrecision: exact, latency: 798, dspName: ]
Banner ad loaded.
[AppLovinSdk] [MAUnityAdManager] Showing [MAAdFormat: BANNER] with ad unit identifier "8axxx58"
..............
[AppLovinSdk] DEBUG [ALErrorReporter] caught_exception reported with code 200
Debug [AppLovin MAX] Invoking event: OnBannerAdRevenuePaidEvent. Params: 8axxx58, [AdInfo adUnitIdentifier: 8axxx58, adFormat: BANNER, networkName: AppLovin, networkPlacement: banner_regular, creativeIdentifier: 2xxx2, placement: , revenue: 0,000220700964331627, revenuePrecision: exact, latency: 798, dspName: ]
Banner ad revenue paid.
[AppLovinSdk] ERROR [ALSdk] Developer passed nil instead of ALAd instance - please check object types!
[AppLovinSdk] ERROR [ALSdk] Called with an invalid object type from: (
        0 0x0000000105389010 +[ALUtils assertValidAd:] + 208
	1  0x00000001052c596c -[ALAdView render:] + 60
	2  0x000000010529bc48 __55-[ALAppLovinAdapterAdViewDelegate adService:didLoadAd:]_block_invoke + 456
	3  0x000000010529ba28 -[ALAppLovinAdapterAdViewDelegate adService:didLoadAd:] + 180
	4  UnityFramework                      0x000000010f136d90 __70+[ALDelegateCallbackInvoker invokeAdLoadDelegate:adService:didLoadAd:]_block_invoke + 28
	5   Foundation                          0x000000018f7f4fa8 0D9893A4-5804-3F0D-BB3F-73989EA36AD3 + 1253288
          .....................
          
[AppLovinSdk] ERROR [ALDelegateCallbackInvoker] Unable to notify ad delegate about ad being loaded : Passed an object of type other than ALAd: ALAdServerAd.

**Comment by romas34** [comment]
The whole problem is with the Facebook plugin version 16.0.2. Doesn't work with him!
Downgrade Facebook plugin to version 15.1.0 solved the problem. In this case, the option "Add use_frameworks! to Podfile" MUST BE Checked!
![изображение](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/31728768/e97c5408-cd40-44cb-8e0b-6bd78bfbc3f1)
