### ISSUE TITLE
Interstitial Ad will be closed when switch the app to background and click the app icon from home page

### ISSUE THREAD

**Issue by xiaoxiaotudou** [AppLovin/AppLovin-MAX-Unity-Plugin#250]
### MAX Plugin Version

5.3.0

### Unity Version

2019.4.22f1

### Device/Platform Info

Android 12, samsung SM-E5260

### Current Behavior

**Interstitial Ad will be closed** when switch the app to background and click the app icon from home page.

### Expected Behavior

when switch the app to background and click the app icon from home page, **the Interstitial Ad continue to show and play.**

I test it for native android. It works normal. The Interstitial Ad will not be broken and continue to show and play.

### How to Reproduce

1. Use official max unity demo and compile it into Android APK.
2. Install the Android APK and launch the app.
3. Load and show Interstitial Ad.
4. Switch the application to the background when the Interstitial Ad played.
5. Find the app on your phone's Home page and click the app.
6. The app launched and the Interstitial Ad showed in step 4 will be closed.

### Additional Info

The recorder for Max Unity Demo
https://user-images.githubusercontent.com/35295273/234841999-8704d630-b2aa-4972-bb8c-f448db57c345.mp4

The recorder for Native Max Android Demo
https://user-images.githubusercontent.com/35295273/234843115-95face3d-9f87-46dd-8d09-0db12ef00433.mp4

**Comment by alvarshahanji** [comment]
@xiaoxiaotudou 
This is expected as Unity uses android:launchMode="singleTask" for their Activity. If you foreground the app through the task switcher/recent apps menu the top Activity is resumed. If you open it via the app icon, the launch Activity gets started which with launchMode singleTask then causes the Android OS to clear all Activities in the stack including the ad that's showing.
Since Unity only supports singleTask as the launchMode there's no way to change this behavior.
