### ISSUE TITLE
Please open issues #27, #28, #29 and fix them

### ISSUE THREAD

**Issue by N0lex** [AppLovin/AppLovin-MAX-Unity-Plugin#30]
@thomasmso, You say that you are not related to the development / support of adapters (Vungle, UnityAds, etc..). But this is not true.

Reply from **Vungle**:
May 29, 2020, 12:29:06 PM PDT 

> **MAX-Vungle adapter was developed by MAX and the github space you are using is owned by MAX.** 
> I am trying to see if this issue happe......

**Please open issues and help resolve issues:**
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/27
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/28
https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/29

Why are you ignoring these problems?

**Comment by thomasmso** [comment]
The problems were passed onto the Vungle and UnityAds teams by your team. Again, for example, if Vungle's SDK crashes or shows an ad that could not easily be closed, our SDK / adapter cannot do anything about it since we aren't exposed to the underlying implementation details of their SDKs. Thus, only the owners of those SDKs can address the issues.
