### ISSUE TITLE
Mediation Unity Ads Adapter 4.9.2.0 make Resolving Android Dependency loop not end. ( version 4.7.1.0 and below work normal)

### ISSUE THREAD

**Issue by trungsteven** [AppLovin/AppLovin-MAX-Unity-Plugin#307]
### MAX Plugin Version

5.11.5

### Unity Version

2022.3.6f1

### Device/Platform Info

Android

### Current Behavior

![image](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/assets/81675566/45aca3e9-bca4-41aa-8fc0-7f7646e03fe1)

### How to Reproduce

add Mediation Unity Ads Adapter 4.9.2.0 make this bug

**Comment by truongntsotanext** [comment]
I had the same problem. It seems that UnityAds is trying to add something that leads to conflicts between downloaded libraries. This makes library files impossible to import into the project.

**Comment by laststare** [comment]
Same problem, I can't find a solution for two weeks

**Comment by Weiky23** [comment]
I have exactly the same issue.
Consider trying another Unity version.
In Unity 2021.3.17, it gets stuck whether the 'Custom Main Gradle Template' is enabled or not. Meanwhile, in Unity 2021.3.32, it gets stuck when the 'Custom Main Gradle Template' is disabled, but it succeeds when this option is enabled.

**Comment by richashukla23** [comment]
The problem stems from EDM's inability to resolve dependencies, which is outside our capacity to rectify. However, we highly advise changing the approach to allow EDM to patch the build.gradle file, rather than relying on direct resolution.

To implement this, activate the 'Custom Main Gradle Template' found under PlayerSettings > Publishing Settings. Then, in the EDM Android Resolver Settings, enable the option to 'Patch mainTemplate.gradle'.

**Comment by uchar** [comment]
@richashukla23 I don't think it's because of EDM, it only happens after upgrading adapter
