### ISSUE TITLE
Can you provide upm installation support?

### ISSUE THREAD

**Issue by 494311870** [AppLovin/AppLovin-MAX-Unity-Plugin#64]
It seems possible to modify the code related to Mediation, but I don't want to modify your code every time you update.

**Comment by santoshbagadi** [comment]
Hi, we do have plans to add UPM support for our plugins but we don't have a timeline for it yet. I'll update this thread once we add UPM support.

**Comment by uchar** [comment]
@santoshbagadi  Same as https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/150 and https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/issues/64 
It would be very beneficial if you could do it sooner, We use the same AppLovin logic for different projects and because of this issue we have to duplicate them all across various projects

**Comment by ErnSur** [comment]
Any news on that?

**Comment by Drecik** [comment]
Any news on that?

**Comment by laicasaane** [comment]
It's been a very long while. Our projects now utilize UPM for everything 2nd and 3rd party. Having to manually make a tgz file out of unitypackage is too menial now. Please at least distribute an additional tgz format.

**Comment by tuha263** [comment]
same here

**Comment by santoshbagadi** [comment]
Hi All, sorry for all the delays here. We have a lot of custom logic in our Integration manager which prevents us from just creating a tgz file and sharing it. 

But we should have a UMP supported SDK out this summer.

**Comment by JonathanLiuApp** [comment]
We've just released plugin [version 8.0.0](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/releases/tag/release_8_0_0) which includes UPM support.
