### ISSUE TITLE
IOS doesnt show ads

### ISSUE THREAD

**Issue by vailshnast** [AppLovin/AppLovin-MAX-Unity-Plugin#65]
Hi! Applovin Max plugin works fine with Android Test Mode. But on ios on realease mode it doesnt seem to work.

Attempt to show ads in mediation debugger are ending with error -1.

The only error i found in logs is 021-06-14 00:27:03.243239+0300 FishWave[1267:192074] [AppLovinSdk] ERROR [ALIncentivizedInterstitialAd] Attempted to display a non-incentivized ad using ALIncentivizedInterstitialAd: [ALAd #20379349167807107 source=5, zoneIdentifier=(null), size=[ALAdSize: INTER], type=[ALAdType: VIDEOA]]

But i have no idea how to fix this stuff. Thanks in advance

![photo_2021-06-14_01-22-24](https://user-images.githubusercontent.com/23454812/121925681-d7175480-cd45-11eb-9054-5f3edea7ba20.jpg)

[ApplovinIOSLogs.txt](https://github.com/AppLovin/AppLovin-MAX-Unity-Plugin/files/6649789/ApplovinIOSLogs.txt)

**Comment by alvarshahanji** [comment]
@vailshnast thanks for reaching out. 
If you are using Unity,
Please update to the External Dependency Manager to minimum version 1.2.164.

Open the iOS Resolver Settings (Assets > External Dependency Manager > iOS Resolver > Settings) and make sure you uncheck Add use_frameworks! to Podfile and Always add the main target to Podfile as in the attached screenshot.
<img width="512" alt="podfile_error" src="https://user-images.githubusercontent.com/48224559/121929908-993f0f80-ccf6-11eb-952a-61a146b0feb1.png">


Otherwise update the podfile manually: 
  target 'Unity-iPhone' do
  end

  use_frameworks!

The above needs to be removed from the podfile. Instead it should look like this:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '11.0'

target 'UnityFramework' do
  pod 'AppLovinMediationAdColonyAdapter', '4.5.0.0.3'
  pod 'AppLovinMediationChartboostAdapter', '8.4.0.1'
  pod 'AppLovinSDK', '6.15.2'
...
end

Let us know how it goes.

**Comment by vailshnast** [comment]
@alvarshahanji  External Dependency Manager was already of that version you`ve mentioned, i`ve unchecked everything you showed, and it worked. Much thanks! I wish i could buy you some beer :)

**Comment by AnyMindG** [comment]
Hi, so we recently updated the AppLovinMax plugin for Unity to the latest version, i.e 11.8.2 for both Android and iOS. But, we are facing some issues in generating a working iOS build. Please find attached screenshots of the errors generated in Xcode due to AppLoviMax plugin.
<img width="570" alt="Screenshot 2023-03-20 at 3 50 24 PM" src="https://user-images.githubusercontent.com/111370321/226312203-bbff149a-0635-42ee-a825-08198d715d1a.png">
<img width="257" alt="Screenshot 2023-03-20 at 3 50 16 PM" src="https://user-images.githubusercontent.com/111370321/226312227-1c7f04a7-7077-4ba3-a59a-f5734155203b.png">
