### ISSUE TITLE
Application crash after some seconds

### ISSUE THREAD

**Issue by Usslessvoid** [AppLovin/AppLovin-MAX-Unity-Plugin#68]
Thread 1: "Passed an object of type other than ALAd: ALAdServerAd."

**Comment by santoshbagadi** [comment]
Hi @Usslessvoid , the issue is caused due to some settings from External Dependency Manager.

To fix this issue, please open the iOS Resolver Settings (**Assets > External Dependency Manager > iOS Resolver > Settings**) and make sure you uncheck Add `use_frameworks! to Podfile` and `Always add the main target to Podfile` as shown below:
<img width="512" alt="Screen Shot 2021-02-26 at 09 46 08" src="https://user-images.githubusercontent.com/37196391/123334982-afb84880-d4f8-11eb-9158-36b742ade92f.png">

**Comment by Usslessvoid** [comment]
Thank you very much 👍

пт, 25 июн. 2021 г., 00:32 Santosh Bagadi ***@***.***>:
