### ISSUE TITLE
Banners do not load

### ISSUE THREAD

**Issue by revolt3r** [AppLovin/AppLovin-MAX-Unity-Plugin#86]
![image](https://user-images.githubusercontent.com/11783754/140766080-fbd4b302-e9a2-4ab1-9729-00108852e081.png)

**Comment by santoshbagadi** [comment]
Hi @revolt3r, I think the most likely issue is that you are using a non-banner ad unit ID to load a banner ad. Could you please double check that you are using the right ad unit ID.

If that is not the case, could you please provide the AppLovin Android SDK version you are using so that we can investigate further.

**Comment by revolt3r** [comment]
You were right, my bad. I was using the wrong ad unit Id.
Thanks for the help!
